### ISSUE TITLE
[ixia-c-controller HELM] Can not set replicaCount

### ISSUE THREAD

**Issue by dgalan-xxia** [open-traffic-generator/ixia-c-helm#1]
https://github.com/open-traffic-generator/ixia-c-helm/blob/main/src/ixia-c-controller/templates/deployment.yaml#L10 - the deployment reads the replicaCoun value from an entry named controller.
But in https://github.com/open-traffic-generator/ixia-c-helm/blob/main/src/ixia-c-controller/values.yaml the property is not defined under controller

**Comment by shramroy** [comment]
The fix is available from release Release v0.0.3
