### ISSUE TITLE
[ixia-c-traffic-engine HELM] fix initContainers

### ISSUE THREAD

**Issue by dgalan-xxia** [open-traffic-generator/ixia-c-helm#3]
If this initialization is not mandatory/doesn;t apply for everyone, then:

#1 I recommend removing this completely from values and leave it in the deployment, but make sure it uses a repository available to all your customers (it's now using keysight artifactory docker-remote.artifactorylbj.it.keysight.com/busybox:latest)

or, if it;s not something that every deployment/scenario would use, then:

#2 leave it exposed in values, but give it a more generic name and allow the users to configure what it's supposed to do; also, do not configure an init container in the deployment if nothing specified in values

**Comment by shramroy** [comment]
The fix is available from release Release v0.0.3
